remote_theme: just-the-docs/just-the-docs
title: AlongTrack Simulator
description: Ground track simulator for altimetry missions

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
